name: stagning

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        run: docker build -t app:latest -f data/docker/Dockerfile .
      - name: Docker run
        env:
          STAGE: STAGING
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: docker run app:latest
