name: Test

on:
  push:
    branches:
      - main

branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build
        run: docker build -t odds-api-data .
      - name: Docker run
        run: docker run odds-api-data
